# Generated by Django 5.0.14 on 2026-08-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del evento')),
                ('tipo', models.CharField(choices=[('boda', 'Boda'), ('xv', 'XV Años'), ('cumpleaños', 'Cumpleaños'), ('corporativo', 'Corporativo'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y hora inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y hora fin')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto (Bs)')),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('confirmado', 'Confirmado'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20)),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas internas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='clientes.cliente')),
                ('empleados_asignados', models.ManyToManyField(blank=True, related_name='eventos', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
