# Generated by Django 5.0.14 on 2026-08-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('paquetes', '0002_alter_detallepaquete_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='paquetes.paquete', verbose_name='Paquete'),
        ),
    ]
