# Generated by Django 5.0.14 on 2026-08-28 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_paquete'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='servicios.servicio', verbose_name='Servicio'),
        ),
    ]
