# Generated by Django 5.0.14 on 2026-08-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionalEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del adicional')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario (Bs)')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionales', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Adicional de evento',
                'verbose_name_plural': 'Adicionales de evento',
            },
        ),
    ]
