# Generated by Django 5.0.14 on 2026-08-25 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del rol')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('puede_ver_dashboard', models.BooleanField(default=False)),
                ('puede_gestionar_clientes', models.BooleanField(default=False)),
                ('puede_gestionar_servicios', models.BooleanField(default=False)),
                ('puede_gestionar_sesiones', models.BooleanField(default=False)),
                ('puede_gestionar_empleados', models.BooleanField(default=False)),
                ('puede_gestionar_pagos', models.BooleanField(default=False)),
                ('puede_gestionar_agenda', models.BooleanField(default=False)),
                ('puede_gestionar_eventos', models.BooleanField(default=False)),
                ('puede_ver_finanzas', models.BooleanField(default=False)),
                ('puede_ver_reportes', models.BooleanField(default=False)),
                ('puede_gestionar_usuarios', models.BooleanField(default=False)),
                ('puede_gestionar_roles', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='permisos.rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de usuario',
                'verbose_name_plural': 'Roles de usuarios',
            },
        ),
    ]
