# Generated by Django 5.0.14 on 2026-08-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la sesión')),
                ('hora', models.TimeField(verbose_name='Hora de la sesión')),
                ('lugar', models.CharField(blank=True, default='', max_length=250, verbose_name='Lugar')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='clientes.cliente')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='empleados.empleado', verbose_name='Fotógrafo asignado')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Sesión fotográfica',
                'verbose_name_plural': 'Sesiones fotográficas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
