# Generated by Django 5.0.14 on 2026-08-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto (Bs)'),
        ),
    ]
