# Generated by Django 5.0.14 on 2026-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0002_sesion_presupuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='presupuesto',
        ),
        migrations.AddField(
            model_name='sesion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio (Bs)'),
        ),
    ]
