# Generated by Django 5.0.14 on 2026-08-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del paquete')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio total (Bs)')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetallePaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario (Bs)')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_paquete', to='servicios.servicio')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='paquetes.paquete')),
            ],
            options={
                'verbose_name': 'Detalle de paquete',
                'verbose_name_plural': 'Detalles de paquetes',
                'unique_together': {('paquete', 'servicio')},
            },
        ),
    ]
