# Generated by Django 5.0.14 on 2026-08-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallepaquete',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='detallepaquete',
            name='descripcion',
            field=models.CharField(default=1, max_length=200, verbose_name='Descripción del item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='servicio_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='servicios.servicio', verbose_name='Servicio principal'),
        ),
        migrations.RemoveField(
            model_name='detallepaquete',
            name='servicio',
        ),
    ]
