# Generated by Django 5.0.14 on 2026-08-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido', models.CharField(blank=True, default='', max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('ci', models.CharField(blank=True, default='', max_length=30, verbose_name='CI / Carnet')),
                ('ciudad', models.CharField(blank=True, default='', max_length=150, verbose_name='Ciudad')),
                ('direccion', models.CharField(blank=True, default='', max_length=250, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-creado'],
            },
        ),
    ]
