# Generated by Django 5.0.14 on 2026-08-25 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Fecha')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo inicial (Bs)')),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo final (Bs)')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas de cierre')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('materiales', 'Materiales de fotografía'), ('arriendo', 'Arriendo de estudio'), ('servicios', 'Servicios básicos'), ('transporte', 'Transporte'), ('marketing', 'Marketing/publicidad'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto/Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs)')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('comprobante', models.CharField(blank=True, default='', max_length=100, verbose_name='Comprobante/Factura')),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('sesion_foto', 'Sesión fotográfica'), ('evento', 'Evento'), ('servicio', 'Servicio'), ('paquete', 'Paquete'), ('otro', 'Otro')], default='sesion_foto', max_length=50)),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto/Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs)')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, default='', max_length=100, verbose_name='Referencia (recibo, etc)')),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ServicioBasico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agua', 'Agua'), ('electricidad', 'Electricidad'), ('gas', 'Gas'), ('internet', 'Internet'), ('telefono', 'Teléfono'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('mes_año', models.CharField(max_length=10, verbose_name='Mes/Año (MM/YYYY)')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (Bs)')),
                ('referencia_pago', models.CharField(blank=True, default='', max_length=100, verbose_name='Referencia de pago')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio básico',
                'verbose_name_plural': 'Servicios básicos',
                'ordering': ['-mes_año'],
                'unique_together': {('tipo', 'mes_año')},
            },
        ),
        migrations.CreateModel(
            name='PagoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_año', models.CharField(max_length=10, verbose_name='Mes/Año (MM/YYYY)')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto base (Bs)')),
                ('bonificación', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bonificación (Bs)')),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuentos (Bs)')),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total a pagar (Bs)')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto pagado (Bs)')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial')], default='pendiente', max_length=20)),
                ('comprobante', models.CharField(blank=True, default='', max_length=100, verbose_name='Comprobante/Transferencia')),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Pago de empleado',
                'verbose_name_plural': 'Pagos de empleados',
                'ordering': ['-mes_año'],
                'unique_together': {('empleado', 'mes_año')},
            },
        ),
    ]
