# Generated by Django 5.0.14 on 2026-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='categoria',
            field=models.CharField(choices=[('wifi', 'WiFi / Internet'), ('agua', 'Agua'), ('luz', 'Luz / Electricidad'), ('gas', 'Gas'), ('tienda', 'Gastos de la tienda'), ('estudio', 'Gastos del foto estudio'), ('materiales', 'Materiales de fotografía'), ('transporte', 'Transporte'), ('marketing', 'Marketing/publicidad'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
    ]
