# Generated by Django 5.0.14 on 2026-08-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_egreso_categoria'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingreso_financiero', to='pagos.pago'),
        ),
    ]
