# Generated by Django 5.0.14 on 2026-08-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_ingreso_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoempleado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
    ]
