# Generated by Django 5.0.14 on 2026-08-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='eventos.evento'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto pagado (Bs)'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto total (Bs)'),
        ),
    ]
